

# For all dates/times

# Observed = amount of time (s) both species called together

# Expected = a null distribution generated by repeated shuffling of the order of each species' observed calling durations with random between-call intervals

# Start by ignoring recorder because we don't know how far they can hear each others' calls?

# Read in the .csv file with the data
AllHornBillData <- read.csv('KennedyEtAlHornBillData.csv')

# Check the structure of the resulting data
head(AllHornBillData)

# Create a new column that has only the hour in which calls were detected
AllHornBillData$Hour = str_split_fixed(AllHornBillData$Start.time,
                                       pattern = ':',n=3)[,1]


# Subset so only have detections
AllHornBillDataCallsOnly <- droplevels(subset(AllHornBillData, Call.type !='none'))

# Convert duration to R friendly format
MinutestoSeconds <- as.numeric(str_split_fixed(AllHornBillDataCallsOnly$Duration,pattern = ':',n=3)[,2])*60
Seconds <- as.numeric(str_split_fixed(AllHornBillDataCallsOnly$Duration,pattern = ':',n=3)[,3] ) 

# Add a new column to the dataframe
AllHornBillDataCallsOnly$CallDur <- MinutestoSeconds+Seconds


DateIndex <- unique(AllHornBillData$Date)

ProportionOverlap <- data.frame()
for(a in 1:length(DateIndex)){
  
  AllHornBillDataCallsOnlyTemp <- subset(AllHornBillDataCallsOnly, Date == DateIndex[a])
  
  AllHornBillDataCallsOnlyTemp <- AllHornBillDataCallsOnlyTemp[order(AllHornBillDataCallsOnlyTemp$Start.time),]
  
  Nrows <- nrow(AllHornBillDataCallsOnlyTemp) -1
  if(Nrows > 1){
  for( b in 1: Nrows){
    Temprow1 <- AllHornBillDataCallsOnlyTemp[b,]
    Temprow2 <- AllHornBillDataCallsOnlyTemp[b+1,]
    
    
    # Want to know if the calls overlap
    CallsOverlap <- strptime(Temprow2$Start.time, "%H:%M:%S") < strptime(Temprow1$End.time, "%H:%M:%S")
    SameSpecies <- Temprow1$Call.type == Temprow2$Call.type
    
    if(CallsOverlap==TRUE & SameSpecies==FALSE){
      Overlap <- 'TRUE'
      
      DurationOverlap <-  strptime(Temprow1$End.time, "%H:%M:%S") - strptime(Temprow2$Start.time, "%H:%M:%S")
      
      TimeAttributes <- attributes(DurationOverlap)
      
      if(TimeAttributes$units =="mins"){
        DurationOverlap <-DurationOverlap*60
      }
      
      if(DurationOverlap > Temprow2$CallDur ){
        DurationOverlap <- Temprow2$CallDur
      }
      
      Temprow1 <- cbind.data.frame(Temprow1,Overlap,DurationOverlap)
      ProportionOverlap <- rbind.data.frame(ProportionOverlap,Temprow1)
    } else {
      Overlap <- 'FALSE'
      DurationOverlap <- 0
      Temprow1 <- cbind.data.frame(Temprow1,Overlap,DurationOverlap)
      ProportionOverlap <- rbind.data.frame(ProportionOverlap,Temprow1)
      
    }
   
  }
  
 } else {
    if(nrow(AllHornBillDataCallsOnlyTemp) > 0){
    Overlap <- 'FALSE'
    DurationOverlap <- 0
    AllHornBillDataCallsOnlyTemp <- cbind.data.frame(AllHornBillDataCallsOnlyTemp,Overlap,DurationOverlap)
    ProportionOverlap <- rbind.data.frame(ProportionOverlap,AllHornBillDataCallsOnlyTemp)
    }
  }

  }

table(ProportionOverlap$Overlap)

OverlapTrue <- subset(ProportionOverlap,Overlap =='TRUE')

CallAfter <- ProportionOverlap[which(ProportionOverlap$Overlap =='TRUE')+1,]

CombineCallsActual <- rbind.data.frame(OverlapTrue,CallAfter)

CombineCallsActual[order(CombineCallsActual$Start.time),]

sum(CombineCallsActual$DurationOverlap)

# Loop to randomize 

library(lubridate)

# Create a series of dates and times within the range of existing data
possible_dates <- seq(as.POSIXct('2018/02/13'), as.POSIXct('2018/04/11'), by="1 secs")

# Create empty list to store values
SimOverlapList <- list()

for(z in 1:500){

# Randomly sample the number of calls in our existing data set
PossibleDatesSub <- sample(possible_dates, nrow(AllHornBillDataCallsOnly),replace = TRUE)

# Create a column for date
Date <- as.Date(PossibleDatesSub)

# Create an end time value using the duration calculated earlier
Endtime <- PossibleDatesSub + seconds(CallDur)

# Create new dataframe
SimulatedHornBillDataCalls <- cbind.data.frame(Date,PossibleDatesSub,Endtime,AllHornBillDataCallsOnly$Call.type,CallDur)

# Add new column names
colnames(SimulatedHornBillDataCalls) <- c('Date','Start.time','End.time','Call.type','CallDur')

# Create a date index
SimDateIndex <- unique(SimulatedHornBillDataCalls$Date)

# Create empty dataframe
SimProportionOverlap <- data.frame()

# Loop to identify calls that overlap temporally
for(a in 1:length(SimDateIndex)){
  
  # Subset based on date; remove any NAs
  SimulatedHornBillDataCallsTemp <- na.omit(subset(SimulatedHornBillDataCalls, Date == SimDateIndex[a]))
  
  # Sort calls based on start time
  SimulatedHornBillDataCallsTemp <- SimulatedHornBillDataCallsTemp[order(SimulatedHornBillDataCallsTemp$Start.time),]
  
  # Calculate number of rows
  Nrows <- nrow(SimulatedHornBillDataCallsTemp) -1
  if(Nrows > 1){
    for( b in 1: Nrows){
      Temprow1 <- SimulatedHornBillDataCallsTemp[b,]
      Temprow2 <- SimulatedHornBillDataCallsTemp[b+1,]
      
      
      # Want to know if the calls overlap
      
      CallsOverlap <- Temprow2$Start.time < Temprow1$End.time
      SameSpecies <- Temprow1$Call.type == Temprow2$Call.type
      
      if(CallsOverlap==TRUE & SameSpecies==FALSE){
        Overlap <- 'TRUE'
        
        DurationOverlap <- Temprow2$Start.time - Temprow1$End.time
        
        if(DurationOverlap > Temprow2$CallDur ){
          
          DurationOverlap <- Temprow2$CallDur
        }
        
        TimeAttributes <- attributes(DurationOverlap)
        
        if(TimeAttributes$units =="mins"){
          DurationOverlap <- DurationOverlap*60
        }
        
        Temprow1 <- cbind.data.frame(Temprow1,Overlap,DurationOverlap)
        SimProportionOverlap <- rbind.data.frame(SimProportionOverlap,Temprow1)
      } else {
        Overlap <- 'FALSE'
        DurationOverlap <- 0
        Temprow1 <- cbind.data.frame(Temprow1,Overlap,DurationOverlap)
        SimProportionOverlap <- rbind.data.frame(SimProportionOverlap,Temprow1)
        
      }
      
    }
    
  } else {
    if(nrow(SimulatedHornBillDataCallsTemp) > 0){
      Overlap <- 'FALSE'
      DurationOverlap <- 0
      SimulatedHornBillDataCallsTemp <- cbind.data.frame(SimulatedHornBillDataCallsTemp,Overlap,DurationOverlap)
      SimProportionOverlap <- rbind.data.frame(SimProportionOverlap,SimulatedHornBillDataCallsTemp)
    }
  }
  
}


OverlapTrue <- subset(SimProportionOverlap,Overlap =='TRUE')

CallAfter <- SimProportionOverlap[which(SimProportionOverlap$Overlap =='TRUE')+1,]

CombinedCalls <- rbind.data.frame(OverlapTrue,CallAfter)

OverlapValue <- sum(abs(CombinedCalls$DurationOverlap))

SimOverlapList[[z]] <- OverlapValue
print(OverlapValue)
}


library(ggpubr)
SimOverlapVals <- unlist(SimOverlapList)
ggdensity(data=SimOverlapVals) + geom_vline(xintercept = sum((CombineCallsActual$DurationOverlap)), col='red' )+xlim(500,3500)
